var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                                                             x  ",
   "                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      x  ",
   "                             xx   xxxxxx                               x     x  ",
   "                              x   x                                     xxxxxx  ",
   "                        xx    x   x       xxxxxxxxxx             x           x  ",
   "  x                xx         x    x               x xx   xxxxxxx            x  ",
   "  x             xx             x   xxxxx           x    x               r x  x  ",
   "  x          xxx               x            x           x                 x  x  ",
   "  x  @     x                   x            x           x        xxxxx    x ox  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx  ",
   "                              x   x                                             ",
   "                              x!!!x                                             ",
   "                              x!!!x                                             ",
   "                              xxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "             xx       xx    r   x   x    xx    x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x      xx       x   x!!!x     r         x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx   xx         x     x               x           x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xx!!!!!xx!!!!!!!!xx!!!!x!!!!!!!!!!!!!!!x           x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx!!!!!!!xxxxxxxxxx!!!!!x!!!!!!!xx!!!!!!xxxxxxxxxxxxx xx   o   xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!xx!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx                     ",],
  ["                                                                          ",
   "                                                                          ",
   "                                                                          ",
   "                                                                          ",
   "                                                                          ",
   "                             xxx xxx xxx xxx                              ",
   "                             x xxx x x xxx x                              ",
   "                             x             x                              ",
   "                             xx           xx                              ",
   "  xxx                         x     x     x                          xxx  ",
   "  x x                         x    xxx    x                          x x  ",
   "  x                           x    xxx    x                            x  ",
   "  x                           x           x                            x  ",
   "  x                           xx          x                            x  ",
   "  x                                       x                            x  ",
   "  x                 x      r              x                            x  ",
   "  x                xxx        xx          x                            x  ",
   "  x                 x         x    xxx    x                            x  ",
   "  x                xxx        xxxxxxxxxxxxx                            x  ",
   "  x      @          x         x           x!!!!!xox!!!!!!!!!!!!!!!!!!!!x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                    ",
   "                                                                    ",
   "                        xxx             xxx                         ",
   "                        xxx             xxx                         ",
   "x		                                                           x",
   "x                                                                  x",
   "x                                                                  x",
   "x                          x           x                           x",
   "x                           xx       xx                            x",
   "                              xxxxxxx                              x",
   "                                                                   x",
   "x@                                                                 x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
